//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Название")]
        public string Title { get; set; }
        [Display(Name = "Год")]
        public short Year { get; set; }
        [Display(Name = "Длительность")]
        public short Length { get; set; }
        [Display(Name = "Описание")]
        public string Description { get; set; }
        [Display(Name = "Рейтинг")]
        public short Rate { get; set; }
        public int Genre_Id { get; set; }

        [Display(Name = "Жанр")]
        public virtual Genre Genre { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
