//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public string FName { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
